#!/bin/bash

echo "Cur dir: $(pwd)"

mkdir /tmp/WNodePython
rsync -av "/home/kevin/ws_cloud/Programme Python/WNodePython/pysmartnode" /mnt/b/WNodePython/ --delete --exclude=__pycache__ --exclude=.git --exclude=.gitignore --exclude=.project --exclude=.pydevproject --exclude=*.mpy --exclude=*.md --exclude=*.bin
rsync -av "/home/kevin/ws_cloud/Programme Python/WNodePython/_testing" /mnt/b/WNodePython/ --delete --exclude=__pycache__ --exclude=.git --exclude=.gitignore --exclude=.project --exclude=.pydevproject --exclude=*.mpy --exclude=*.md --exclude=*.bin
rsync -av "/home/kevin/ws_cloud/Programme Python/WNodePython/external_modules" /mnt/b/WNodePython/ --exclude=*.egg-info --exclude=.git --exclude=.gitignore --exclude=.project --exclude=.pydevproject --exclude=*.mpy --exclude=*.md --exclude=*.bin

cd /mnt/b/WNodePython
for d in pysmartnode _testing external_modules 
do
for f in $(find ./$d -name *.py); do
~/MicroPython_ESP32_psRAM_LoBo/MicroPython_BUILD/components/micropython/mpy-cross/mpy-cross $f;
rm $f
echo $f
done
done
echo "generated bytecode"