# Author: Kevin Köck
# Copyright Kevin Köck 2019 Released under the MIT license
# Created on 2019-10-12 

__updated__ = "2019-10-16"
__version__ = "0.2"

# IMPLEMENTED MODES
MODE_OFF = "off"
MODE_HEAT = "heat"
MODES_SUPPORTED = [MODE_OFF, MODE_HEAT]

# ACTION STATES
ACTION_OFF = "off"
ACTION_HEATING = "heating"
ACTION_COOLING = "cooling"
ACTION_DRYING = "drying"
ACTION_IDLE = "idle"
ACTION_FAN = "fan"
ACTIONS = [ACTION_OFF, ACTION_HEATING, ACTION_COOLING, ACTION_DRYING, ACTION_IDLE, ACTION_FAN]

# AWAY MODES
AWAY_OFF = "OFF"
AWAY_ON = "ON"

# CLIMATE STATE ATTRIBUTES
CURRENT_TEMPERATURE_LOW = "c_temp_l"
CURRENT_TEMPERATURE_HIGH = "c_temp_h"
AWAY_MODE_STATE = "away"
STORAGE_AWAY_TEMPERATURE_LOW = "_a_temp_l"
STORAGE_AWAY_TEMPERATURE_HIGH = "_a_temp_h"
STORAGE_TEMPERATURE_LOW = "_temp_l"
STORAGE_TEMPERATURE_HIGH = "_temp_h"
CURRENT_MODE = "mode"
CURRENT_ACTION = "action"
